#pragma config(Motor,  port1,           LeftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          RightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1) {
    motor[LeftMotor] = vexRT[Ch3] / 2;
    motor[RightMotor] = vexRT[Ch2] / 2;
 }



}
