#pragma config(Sensor, dgtl1,  encoderleft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderright,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  encoderc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           motorleft,     tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port6,           catapultr2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           catapultl2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           catapultr1,    tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl5)
#pragma config(Motor,  port9,           catapultl1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          motorright,    tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	clearDebugStream();
	bool store = false;

	int cspeed = -8; //variable for the default speed of the catapult

	int oldangle = 0;
	int newangle = 0;


	while(1==1){


		motor(motorleft) =  vexRT[Ch2] / 2;
		motor(motorright) =  vexRT[Ch3] / 2; //moving the main chasis

		if (store==true){//boolean value for if the robot should be holding a football in storage
			motor(catapultl1) = cspeed;
			motor(catapultr1) = cspeed;
			wait1Msec(50);
			if(SensorValue[dgtl5]> 33){
				if(newangle>=oldangle){
				cspeed -= 1;
			}
			}

			else if(SensorValue[dgtl5]< 40){
				if(newangle<=oldangle){
				cspeed += 1;
			}
			}



		}

		if(vexRT[Btn5D] == 1){ // Button to raise scooper for storage
			store = true;
		}


		if(vexRT[Btn5U] == 1){ // Button to lower scooper from raised position
			store = false;
			motor[catapultl1] = -30;
			motor(catapultr1) = -30;
			wait1Msec(500);
			motor[catapultl1] = 0;
			motor(catapultr1) = 0;
		}

		if(vexRT[Btn6D] == 1){ // Launch program
			motor(motorleft) = -10;
			motor(motorright) = -10;  //kills the motors so that the robot isnt moving uncontrollably while firing
			wait1Msec(80);
			motor(motorleft) = 0;
			motor(motorright) = 0;

			motor[catapultl1] = 127;
			motor(catapultr1) = 127;
			wait1Msec(750);   //fires catapult
														  //brings catapult back
			motor[catapultl1] = 0;
			motor(catapultr1) = 0;
		}


	}



}
