#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           motorleft,     tmotorVex393_HBridge, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port10,          motorright,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	clearDebugStream();
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	SensorType[in8] = sensorGyro;
	wait1Msec(3000);

	int cycles = 100;
	int n = 0;
	int mspeed = 127;

	float distancex = 0;
	float distancey = 0;
	float totalx = 0;
	float totaly = 0;

	int newangle = 0;
	int oldangle = 0;

	int oldrotatel = 0;
	int newrotatel = 0;
	int oldrotater = 0;
	int newrotater = 0;

	int rotatedistl = 0;
	int rotatedistr = 0;

	float distl = 0;
	float distr = 0;

	motor(motorleft) = mspeed;
	motor(motorright) = mspeed;
	while (n < cycles){
		oldangle = newangle;
		newangle = SensorValue[in8];
		oldrotatel = newrotatel;
		newrotatel = SensorValue[dgtl1];
		oldrotater = newrotater;
		newrotater = SensorValue[dgtl3];
		rotatedistl = newrotatel - oldrotatel;
		rotatedistr = newrotater - oldrotater;


	}

	mspeed = 0;
	motor(motorleft) = mspeed;
	motor(motorright) = mspeed;

	while (mspeed >= - 20){
		mspeed = mspeed - 10;
		motor(motorleft) = mspeed;
		motor(motorright) = mspeed;
		wait1Msec(50);
	}
	motor(motorleft) = mspeed;
	motor(motorright) = mspeed;

}
