#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           motorleft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          motorright,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int lnum = 0;
	int rnum = 0; // acting as Boolean values, idk how to do them in Robotc or C++

	int rotations = 10;
	int rotationangle = rotations*360; //the angle through which the encoders should record the wheels turning
	SensorValue[dgtl1] = 0; // clearing any previous readings
	SensorValue[dgtl3] = 0;
	int dftspeed = 50; //default speed

	int cycles = 100;  //Maximum number of times that the robot can adjust its speed

	int leftspeed = dftspeed;
	int rightspeed = dftspeed;

	int newangle = 0;
	int oldangle = 0;
	//int n = 0;

	int distX;
	int distY;

	clearDebugStream();
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	SensorType[in8] = sensorGyro;
	wait1Msec(3000);

	//encoder code
	while(1 == 1){

		oldangle = newangle;
		newangle = SensorValue[in8];
		wait1Msec(100);
		distX += 1;
		if (SensorValue[in8] < 0) {
			if (newangle <= oldangle) {
				rightspeed = rightspeed + 5;
				leftspeed = leftspeed - 2;
			}

		}

		else if (SensorValue[in8] > 0) {
			if (newangle >= oldangle) {
				rightspeed = rightspeed - 2;
				leftspeed = leftspeed + 2;
			}

		}
		else {
			leftspeed = dftspeed;
			rightspeed = dftspeed;

		}


		if (SensorValue[dgtl1] > -1*rotationangle){
			motor(motorleft) = leftspeed;
		}
		else if(SensorValue[dgtl1] < -1*rotationangle){
			leftspeed = 0;
			while (lnum == 0){
				while (leftspeed >= - 20){
					leftspeed = leftspeed - 10;
					rightspeed = rightspeed - 10;
					motor(motorleft) = leftspeed;
					motor(motorright) = rightspeed;//unfortunately, have not found a way to kill both engines independantly and accurately, so both are turned off at the same time.
					wait1Msec(50);
					lnum += 1;
					rnum+=1;
				}
			}
			motor(motorleft) = 0;
			motor(motorright) = 0;

		}
		if (SensorValue[dgtl3] < rotationangle){
			motor(motorright) = rightspeed;
		}
		else if(SensorValue[dgtl3] > rotationangle){
			rightspeed = 0;
			while (rnum == 0){
				while (rightspeed >= - 20){
					rightspeed = rightspeed - 10;
					leftspeed = leftspeed - 10;
					motor(motorright) = rightspeed;
					motor(motorleft) = leftspeed;
					wait1Msec(50);
					rnum+=1;
					lnum+=1;
				}
			}
			motor(motorright) = 0;
			motor(motorleft) = 0;
		}
	}

//striaght line code


}
