#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           motorleft,     tmotorVex393_HBridge, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port10,          motorright,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	clearDebugStream();
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	SensorType[in8] = sensorGyro;
	wait1Msec(3000);

	int dftspeed = 50;

	int cycles = 100;

	int leftspeed = dftspeed;
	int rightspeed = dftspeed;

	int newangle = 0;
	int oldangle = 0;
	int n = 0;

	int lnum = 0;
	int rnum = 0;

	SensorValue[dgtl1] = 0;
	SensorValue[dgtl3] = 0;



}
