#pragma config(Motor,  port1,           Motorleft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          Motorright,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	SensorType[in8] = sensorGyro;
	wait1Msec(3000);

	int turn = 900;
	while(1==1){

		if(SensorValue[in8] < turn) {
			motor(Motorleft) = -50;
			motor(Motorright) =50;

		}

		else if(SensorValue[in8] >= turn) {
			motor(Motorleft) = 5;
			motor(Motorright) = -5;
			wait1Msec(100);
			motor(Motorleft) = 0;
			motor(Motorright) = 0;
		}
	}
}
