#pragma config(Sensor, dgtl1,  limit,          sensorTouch)
#pragma config(Motor,  port1,           motorone,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1 == 1){
		motor(motorone) = 63;
		wait1Msec(3000);
		motor(motorone) = 0;
		wait1Msec(10000);
	}







}
