#pragma config(Motor,  port1,           motorleft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          motorright,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int mspeed = 127;

	motor(motorleft) = mspeed;
	motor(motorright) = mspeed;
	wait1Msec(2000);
	mspeed = 0;
	motor(motorleft) = mspeed;
	motor(motorright) = mspeed;

	while (mspeed >= - 20){
		mspeed = mspeed - 10;
		motor(motorleft) = mspeed;
		motor(motorright) = mspeed;
		wait1Msec(50);
	}
	motor(motorleft) = mspeed;
	motor(motorright) = mspeed;

}
