#pragma config(Sensor, dgtl1,  decodeleft,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  decoderight,    sensorQuadEncoder)
#pragma config(Motor,  port1,           Motorleft,     tmotorVex393_HBridge, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port10,          Motorright,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	clearDebugStream();
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	SensorType[in8] = sensorGyro;
	wait1Msec(3000);

	int dftspeed = 50; //default speed

	int cycles = 100;  //Maximum number of times that the robot can adjust its speed

	int leftspeed = dftspeed;
	int rightspeed = dftspeed;

	int newangle = 0;
	int oldangle = 0;
	int n = 0;

	while(n!=cycles) {
		motor(Motorright) = rightspeed;
		motor(Motorleft) = leftspeed;
		oldangle = newangle;
		newangle = SensorValue[in8];
		wait1Msec(100);
		n += 1;
		if (SensorValue[in8] < 0) {
			if (newangle <= oldangle) {
				rightspeed = rightspeed + 5;
				leftspeed = leftspeed - 2;
			}

		}

		else if (SensorValue[in8] > 0) {
			if (newangle >= oldangle) {
				rightspeed = rightspeed - 2;
				leftspeed = leftspeed + 2;
			}

		}
		else {
			leftspeed = dftspeed;
			rightspeed = dftspeed;

		}
	}


}
