#pragma config(Motor,  port1,           Motorleft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          Motorright,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	SensorType[in8] = sensorGyro;
	wait1Msec(3000);


	int leftspeed = 50;
	int rightspeed = 50;

	int newangle = 0;
	int oldangle = 0;
	int n = 0;

	while(n!=60) {
		motor(Motorright) = rightspeed;
		motor(Motorleft) = leftspeed;
		oldangle = newangle;
		newangle = SensorValue[in8];
		wait1Msec(100);
		n=n + 1;
		if (SensorValue[in8] < 0) {
			if (newangle <= oldangle) {
				rightspeed = rightspeed + 10;
				leftspeed = leftspeed - 5;
			}

		}

		else if (SensorValue[in8] > 0) {
			if (newangle >= oldangle) {
				rightspeed = rightspeed - 5;
				leftspeed = leftspeed + 5;
			}

		}
		else {
			leftspeed = 50;
			rightspeed = 50;

		}
	}




}
