#pragma config(Sensor, dgtl1,  limitswitch,    sensorTouch)
#pragma config(Motor,  port1,  onemotor,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while (1 == 1) {

		if(SensorValue(limitswitch) == 1) {
			motor(onemotor) = 0;
			wait1Msec(10000);

		}

		else {

			motor(onemotor) = -63;
		}
	}

}
